version: '3.8'
services:
  db:
    image: redis:latest
    networks:
      - redis_net
    ports:
      - 6379:6379
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - redis_net
    depends_on:
      - db
    ports:
      - '3000:3000'
networks:
  redis_net:
    driver: bridge
